# taken from https://dev.to/abulka/comment/1dh3k thanks!
name: Release Catalyst
on: workflow_dispatch
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/upload-artifact@v3
        with:
          name: nightly
          path: |
            out/
      - name: Install dependencies
        run: npm install
      - name: Get tailwind styles
        run: npm run tailwind:once
      - name: Build
        run: npm run make
  
